-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 23:52:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema git_it
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema git_it
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `get_it` DEFAULT CHARACTER SET utf8mb4 ;
USE `get_it` ;

-- -----------------------------------------------------
-- Table `git_it`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `get_it`.`usuarios` (
  `idusuarios` INT(15) NOT NULL,
  `nombre` VARCHAR(80) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `clave` varchar(300) NOT NULL,
  `celular` CHAR(15) NULL DEFAULT NULL,
  `direccion` varchar(200), 
  `estado` CHAR(1) NUll DEFAULT 0,
  `img` varchar(255),
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `git_it`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `get_it`.`productos` (
    `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
    `nombre` varchar(80),
    `descripcion` VARCHAR(500) NULL DEFAULT NULL,
    `idusuario` INT(11) NULL DEFAULT NULL,
    `cambiarpor` VARCHAR(500) NULL DEFAULT NULL,
    `canjeadopor` int(11) NULL DEFAULT NULL,
    `estado` CHAR(1) NULL DEFAULT '1',
    `fecha_publ` char(10) NULL DEFAULT NULL,
    `fecha_canje` char(10) NULL DEFAULT NULL,
    `categoria` CHAR(8) NULL DEFAULT NULL,
    `img` varchar(255),
    PRIMARY KEY (`idproducto`),
	FOREIGN KEY `fk_idusuario_producto` (`idusuario`) REFERENCES `usuarios` (`idusuarios`),
    FOREIGN KEY `fk_usuarios_canjeadopor_productos` (`canjeadopor`) REFERENCES `usuarios` (`idusuarios`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8MB4;


CREATE TABLE `procesos_trueque` (
	`idproceso` int(10) not null auto_increment primary key,
    `usuario_dueno` int(15) not null,
    `usuario_solicitante` int(15) not null,
    `producto` int(11),
    `estado` char(1) default '0',
    `datos_cambio_descripcion` text(1000),
    `datos_cambio_ofrezco` varchar(100),
    foreign key `usuarios_idusuarios_procesos` (usuario_dueno) references usuarios(idusuarios),
    foreign key `usuarios_idusuarios2_procesos` (usuario_solicitante) references usuarios(idusuarios),
    foreign key `productos_idproductos_procesos` (producto) references productos(idproducto)
);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
